// ============================================================
// Skip or Solve decision bank (2026-09 flow overhaul).
// The trainer no longer shows options — the student sees ONLY the
// stem and makes a CALL: "Solve it" or "Skip it" within 8 seconds.
// Every item therefore carries a deliberate classification:
//   kind: "scorer" — clean, single-concept, convertible under
//         exam pressure. The right call is SOLVE.
//   kind: "trap"   — long, multi-step, case-heavy or low-yield in
//         8 seconds. The right call is SKIP.
//   why:  one-line rationale, shown on the verdict card and in the
//         end-of-run review.
// The old get_trainer_questions RPC pulled random rows from the
// whole question bank (no trap flag, HTML/image-heavy) — a curated
// local bank is the only way every item can KNOW its right call.
// The full classification list is audited in
// "IPM Careers/Gulp-authored-questions-review.html".
//
// 2026-09 bank expansion: 33 → 120 items (66 scorers / 54 traps;
// QA 54 · LR 36 · VA 30) so the deterministic daily rotation
// (SkipOrSolve.js) runs 12 days before any item repeats. New items
// are audited in "IPM Careers/SkipSolve-bank-expansion-review.html".
// ============================================================

const SOS_BANK = [
  // ── QA scorers ──
  { id: "s01", section: "QA", kind: "scorer", stem: "The average of 5 consecutive even numbers is 40. What is the largest of them?", why: "Consecutive-number averages are a 5-second identity: middle = 40, largest = 44. Free marks.", solution: "The middle (3rd) number equals the average, 40 → numbers are 36…44. Largest = 44." },
  { id: "s02", section: "QA", kind: "scorer", stem: "If 3x − 7 = 2x + 5, what is the value of x?", why: "One-step linear equation, solving takes less time than deciding. Always convert these.", solution: "3x − 2x = 5 + 7 → x = 12." },
  { id: "s03", section: "QA", kind: "scorer", stem: "What is 15% of 240?", why: "Single percentage on a friendly number: 10% + 5% mental math. Clean scorer.", solution: "24 + 12 = 36." },
  { id: "s04", section: "QA", kind: "scorer", stem: "The product of two co-prime numbers is 117. What is their LCM?", why: "Pure definition recall. LCM of co-primes is their product. No computation at all.", solution: "For co-primes, LCM = product = 117." },
  { id: "s05", section: "QA", kind: "scorer", stem: "A shopkeeper buys an article for ₹400 and sells it for ₹460. What is the profit percent?", why: "One clean ratio: 60/400. Single-concept profit percent is always worth the attempt.", solution: "60/400 × 100 = 15%." },
  { id: "s06", section: "QA", kind: "scorer", stem: "How many diagonals does a hexagon have?", why: "Direct formula n(n−3)/2, a memory question dressed as geometry.", solution: "6 × 3 / 2 = 9 diagonals." },
  { id: "s07", section: "QA", kind: "scorer", stem: "If log₁₀ 2 ≈ 0.301, what is log₁₀ 8?", why: "One log identity: log 8 = 3 log 2. Single step, no cases.", solution: "3 × 0.301 = 0.903." },
  { id: "s08", section: "QA", kind: "scorer", stem: "The sum of the first 20 natural numbers is:", why: "n(n+1)/2 is the most-rehearsed formula in the syllabus. Instant conversion.", solution: "20 × 21 / 2 = 210." },
  { id: "s09", section: "QA", kind: "scorer", stem: "A train 200 m long crosses a pole in 10 seconds. What is its speed in m/s?", why: "Crossing a pole = length/time. One division; classic sitter.", solution: "200 / 10 = 20 m/s." },
  { id: "s10", section: "QA", kind: "scorer", stem: "If the ratio of two numbers is 3 : 5 and their sum is 96, what is the smaller number?", why: "Ratio-sum split is a single proportional step, bankable in well under 8 seconds.", solution: "3/8 × 96 = 36." },

  // ── QA traps ──
  { id: "t01", section: "QA", kind: "trap", stem: "Find the number of positive integer solutions of 3x + 5y + 7z = 100 with x, y, z all distinct.", why: "Multi-variable case enumeration with a distinctness condition, minutes of casework, not 8 seconds.", solution: "Requires enumerating (x, y, z) families case by case, exactly the low-yield grind to skip in a timed section." },
  { id: "t02", section: "QA", kind: "trap", stem: "A cistern has three pipes A, B and C. A and B fill it in 12 and 15 hours; C empties it. Opened together at staggered one-hour intervals in the order A, B, C, the tank fills in 8 hours 24 minutes. In how many hours does C alone empty a full tank?", why: "Staggered-start pipes with a fractional total time, a three-equation setup hiding in a story. Textbook time sink.", solution: "Needs hour-by-hour work accounting before C's rate can be isolated, far beyond an 8-second window." },
  { id: "t03", section: "QA", kind: "trap", stem: "How many four-digit numbers with all distinct digits are divisible by 11 and have their digit sum equal to 18?", why: "Two simultaneous number-theory filters plus a distinct-digit sweep. Enumeration-heavy, tiny payoff.", solution: "Divisibility by 11 forces alternating-sum conditions to be crossed with digit-sum 18, pure listing under pressure." },
  { id: "t04", section: "QA", kind: "trap", stem: "The sum of the series 1/(1·3) + 1/(3·5) + 1/(5·7) + … + 1/(97·99), multiplied by the sum 1² − 2² + 3² − 4² + … − 98² + 99², equals:", why: "Two separate series tricks chained together. Either alone is fine; multiplied, it is a deliberate time trap.", solution: "Telescoping gives 49/99; the alternating squares give 4950, but spotting and combining BOTH inside 8 seconds is not a percentage play." },
  { id: "t05", section: "QA", kind: "trap", stem: "A, B and C run around a circular track of 1200 m at speeds 3, 5 and 7 m/s, A and C clockwise, B anticlockwise, all starting together. After how many seconds are all three together at the starting point for the second time?", why: "Three runners, mixed directions, LCM of meeting times, classic multi-layer circular-motion grind.", solution: "Needs individual lap times (400 s, 240 s, ~171.4 s) and their LCM logic, a two-minute question minimum." },
  { id: "t06", section: "QA", kind: "trap", stem: "If x + 1/x = √3, find the value of x²⁰²⁶ + 1/x²⁰²⁶ + x²⁰²³ + 1/x²⁰²³.", why: "Needs the ω/cis-30° periodicity insight plus careful index chasing. Miss one cycle and the −5 is guaranteed.", solution: "x = cis(±30°), so powers cycle with period 12, elegant on paper, brutal on the clock." },
  { id: "t07", section: "QA", kind: "trap", stem: "Three friends invest in a business. The first invests ₹x for 4 months, the second ₹(x + 5000) for 8 months and the third ₹(x − 2000) for the full year. If the annual profit of ₹87,400 is split in proportion and the third receives ₹28,600, find x.", why: "A stacked partnership equation with three unknown-in-terms-of-x capitals, setup alone eats the 8 seconds.", solution: "Requires building 4x : 8(x+5000) : 12(x−2000) and solving the share equation, solvable, but never in 8 seconds." },

  // ── DILR / reasoning ──
  { id: "s11", section: "LR", kind: "scorer", stem: "In a certain code, CAT is written as DBU. How is DOG written in that code?", why: "One uniform +1 letter shift, decode and answer in one pass.", solution: "Each letter moves one ahead: DOG → EPH." },
  { id: "s12", section: "LR", kind: "scorer", stem: "Pointing to a photograph, Ravi says, \"She is the daughter of my grandfather's only son.\" How is the girl related to Ravi?", why: "Single-link blood relation. 'grandfather's only son' collapses to 'father' immediately.", solution: "Grandfather's only son = Ravi's father; his daughter = Ravi's sister." },
  { id: "s13", section: "LR", kind: "scorer", stem: "Find the next term: 2, 6, 12, 20, 30, ?", why: "Differences 4, 6, 8, 10, a first-order pattern visible on sight.", solution: "Differences grow by 2 → next difference 12 → 42." },
  { id: "s14", section: "LR", kind: "scorer", stem: "Statements: All roses are flowers. Some flowers fade quickly. Does the conclusion \"some roses fade quickly\" definitely follow?", why: "A two-statement syllogism with one conclusion to test, the classic invalid 'some' transfer, judgeable on sight.", solution: "Not certain, the fading flowers need not include any roses. The certain answer is that no such conclusion follows." },
  { id: "s15", section: "LR", kind: "scorer", stem: "A clock shows 3:00. What is the angle between the hour and minute hands?", why: "Standard clock position with the minute hand at 12, pure formula recall.", solution: "3 × 30° = 90°." },
  { id: "t08", section: "LR", kind: "trap", stem: "Eight people P–W sit around a circular table, four facing the centre. P sits third to the left of the one facing away opposite Q; exactly two sit between R and S counted clockwise from R; T faces V, who is not adjacent to Q or W. Who sits second to the right of U?", why: "A full facing-direction circular arrangement compressed into one question, this is a 4-minute puzzle set, not one answer.", solution: "Needs the entire seating chart with facing directions resolved before any single position falls out." },
  { id: "t09", section: "LR", kind: "trap", stem: "Five colleagues each made two statements about who broke the printer; exactly one of each person's statements is true and exactly one colleague is guilty. From the ten statements, identify the culprit.", why: "Truth-liar grids demand testing assumptions per suspect. Deep casework in a shallow-time trainer.", solution: "Requires assuming each suspect guilty in turn and checking all ten half-true constraints, pure elimination labour." },
  { id: "t10", section: "LR", kind: "trap", stem: "In a family of nine across three generations with two married couples per generation, M is the only nephew of N, whose mother-in-law O is the paternal grandmother of P… How is Q related to the sister-in-law of M's father?", why: "Nine-member, three-generation tree with in-law links, drawing it costs multiples of your 8 seconds.", solution: "Only a full family tree resolves it; the phrasing is engineered to be unsolvable at a glance." },
  { id: "t11", section: "LR", kind: "trap", stem: "A cube is painted red on two opposite faces, blue on two adjacent faces and left unpainted elsewhere, then cut into 216 smaller cubes. How many small cubes have exactly one blue face and no red face?", why: "6×6×6 painted-cube with mixed adjacent/opposite colouring, visual bookkeeping the clock will not forgive.", solution: "Needs face-by-face accounting of edge overlaps between the blue faces and red neighbours, a grid-paper question." },

  // ── VA scorers & traps ──
  { id: "s16", section: "VA", kind: "scorer", stem: "Choose the word most nearly OPPOSITE in meaning to FRUGAL.", why: "Direct antonym of a core prep-list word, vocabulary is either known or not; no time cost either way.", solution: "FRUGAL means sparing with money, the opposite is extravagant." },
  { id: "s17", section: "VA", kind: "scorer", stem: "Spot the error: \"Each of the students have submitted their assignment.\"", why: "'Each of' + verb agreement is one of the five most-drilled grammar rules. Instant call.", solution: "'Each' is singular → 'Each of the students HAS submitted…'." },
  { id: "s18", section: "VA", kind: "scorer", stem: "Fill in the blank: \"She is quite different ___ her sister.\"", why: "Single preposition-usage rule, no context needed.", solution: "Different FROM her sister." },
  { id: "s19", section: "VA", kind: "scorer", stem: "Choose the correctly spelt word: (a) occassion (b) occasion (c) ocassion (d) occasionn.", why: "Spelling recognition is a look-and-know item, zero working required.", solution: "(b) occasion." },
  { id: "t12", section: "VA", kind: "trap", stem: "Arrange six jumbled sentences (A–F) about the history of central banking into a coherent paragraph, where three sentences begin with pronoun references and two are near-duplicates in theme.", why: "Six-sentence para-jumbles with pronoun webs routinely eat 90+ seconds and still miss. Low yield per second.", solution: "Requires testing multiple orderings against the pronoun chains, the definition of a time trap in VA." },
  { id: "t13", section: "VA", kind: "trap", stem: "A 450-word passage on monetary policy follows, with the question: \"Which of the following, if true, would MOST weaken the author's secondary argument in paragraph three?\"", why: "A full passage read for one inference mark, never convertible in 8 seconds, whatever your reading speed.", solution: "The question demands locating and negating a secondary argument, full-passage work by design." },
  { id: "t14", section: "VA", kind: "trap", stem: "Match eight idioms in Column I with eight scrambled meanings in Column II, then pick the option giving all eight pairs correctly.", why: "All-eight matching means one unknown idiom sinks the whole item. High risk, matrix-checking overhead.", solution: "Even with six known pairs, verifying the full option matrix against the remaining two costs minutes." },

  // ════════════════════════════════════════════════════════════
  // 2026-09 EXPANSION (s20–s66, t15–t54) — original items, register
  // matched to the portal's own mocks; audited in
  // "IPM Careers/SkipSolve-bank-expansion-review.html".
  // ════════════════════════════════════════════════════════════

  // ── QA scorers (expansion) ──
  { id: "s20", section: "QA", kind: "scorer", stem: "A number increased by 20% becomes 96. Find the number.", why: "One reverse-percentage division, 96 ÷ 1.2. Sitters like this fund your rank.", solution: "96 / 1.2 = 80." },
  { id: "s21", section: "QA", kind: "scorer", stem: "The average of 7 numbers is 12. If every number is increased by 6, what is the new average?", why: "Shift rule: add k to each number and the average moves by k. Zero computation.", solution: "12 + 6 = 18." },
  { id: "s22", section: "QA", kind: "scorer", stem: "What is the units digit of 7⁴³?", why: "Powers of 7 cycle every 4, a rehearsed cycle question, not a computation.", solution: "43 mod 4 = 3 → units digit of 7³ = 343 → 3." },
  { id: "s23", section: "QA", kind: "scorer", stem: "Find the simple interest on ₹5,000 at 8% per annum for 3 years.", why: "PRT/100 with round numbers, single formula, free marks.", solution: "5000 × 8 × 3 / 100 = ₹1,200." },
  { id: "s24", section: "QA", kind: "scorer", stem: "Convert 54 km/h into m/s.", why: "×5/18 is muscle memory for any TSD-prepared aspirant.", solution: "54 × 5/18 = 15 m/s." },
  { id: "s25", section: "QA", kind: "scorer", stem: "In how many ways can 5 people be seated in a row of 5 chairs?", why: "Straight factorial, the most basic P&C identity there is.", solution: "5! = 120." },
  { id: "s26", section: "QA", kind: "scorer", stem: "What is the value of log₅ 125?", why: "125 is 5³, the answer is read off, not computed.", solution: "log₅ 5³ = 3." },
  { id: "s27", section: "QA", kind: "scorer", stem: "If a + b = 10 and ab = 21, find a² + b².", why: "One identity: (a + b)² − 2ab. Clean numbers, single substitution.", solution: "100 − 42 = 58." },
  { id: "s28", section: "QA", kind: "scorer", stem: "A price falls from ₹250 to ₹200. What is the percentage decrease?", why: "Change over original, one fraction on friendly numbers.", solution: "50/250 × 100 = 20%." },
  { id: "s29", section: "QA", kind: "scorer", stem: "Find the HCF of 36 and 84.", why: "Two small numbers, one factorisation, a 10-second ceiling even on a bad day.", solution: "36 = 12 × 3, 84 = 12 × 7 → HCF = 12." },
  { id: "s30", section: "QA", kind: "scorer", stem: "A dozen pens cost ₹180. What do 5 pens cost?", why: "Unitary method in one step, never leave these on the table.", solution: "₹15 each → ₹75." },
  { id: "s31", section: "QA", kind: "scorer", stem: "A car covers 240 km in 4 hours. At the same speed, how long will 360 km take?", why: "Constant speed, direct proportion, one ratio and out.", solution: "60 km/h → 360/60 = 6 hours." },
  { id: "s32", section: "QA", kind: "scorer", stem: "If x² − 9 = 0 and x > 0, find x³.", why: "The condition hands you x = 3, the cube is the whole question.", solution: "x = 3 → x³ = 27." },
  { id: "s33", section: "QA", kind: "scorer", stem: "In how many ways can 2 students be chosen from a group of 8?", why: "⁸C₂ is a formula read, not a puzzle.", solution: "8 × 7 / 2 = 28." },
  { id: "s34", section: "QA", kind: "scorer", stem: "Evaluate log₂ 32 + log₂ 2.", why: "Both terms are powers of 2, pure exponent reading.", solution: "5 + 1 = 6." },
  { id: "s35", section: "QA", kind: "scorer", stem: "30% of a number is 45. Find the number.", why: "One division undoes the percentage, never skip arithmetic this clean.", solution: "45 / 0.3 = 150." },
  { id: "s36", section: "QA", kind: "scorer", stem: "Find the area of a circle of radius 7 cm (take π = 22/7).", why: "The radius is chosen to cancel the π, the setter is giving this one away.", solution: "22/7 × 49 = 154 cm²." },
  { id: "s37", section: "QA", kind: "scorer", stem: "₹720 is divided among three people in the ratio 2 : 3 : 4. Find the largest share.", why: "Ratio-total split, one proportional multiplication.", solution: "4/9 × 720 = ₹320." },
  { id: "s38", section: "QA", kind: "scorer", stem: "What is the remainder when 2¹⁰ is divided by 3?", why: "2 ≡ −1 (mod 3), the whole question collapses to (−1)¹⁰.", solution: "(−1)¹⁰ = 1." },
  { id: "s39", section: "QA", kind: "scorer", stem: "What is the sum of the interior angles of a pentagon?", why: "(n − 2) × 180°, formula recall wearing a geometry costume.", solution: "3 × 180° = 540°." },

  // ── QA traps (expansion) ──
  { id: "t15", section: "QA", kind: "trap", stem: "The price of an article is increased by 17.5%, then decreased by 8.4%, then increased by 6.25%, becoming ₹6,438.42. Find the original price.", why: "Three ugly successive multipliers ending in paise, a calculator question in a no-calculator exam. Walk away.", solution: "1.175 × 0.916 × 1.0625 must be unwound against 6,438.42, pure long division under pressure." },
  { id: "t16", section: "QA", kind: "trap", stem: "A boat rows 28 km upstream and 40 km downstream in 14 hours; it rows 21 km upstream and 30 km downstream in 10.5 hours. Find the speed of the stream.", why: "Two equations in two hidden reciprocals, a substitution grind dressed as a boat story.", solution: "Set u and d as reciprocal speeds and solve the 2×2 system, minutes, not seconds." },
  { id: "t17", section: "QA", kind: "trap", stem: "From a vessel containing 91 litres of milk, 7 litres are drawn and replaced with water, and this operation is performed three more times. Then 13 litres of the mixture are removed. How much milk remains?", why: "Repeated replacement plus a final removal, the (12/13)⁴ power alone kills the clock.", solution: "91 × (12/13)⁴, then scale for the final draw, a powers-of-fractions slog." },
  { id: "t18", section: "QA", kind: "trap", stem: "In how many ways can the letters of MANAGEMENT be arranged so that no two vowels are together and the two Ms are never adjacent?", why: "Two simultaneous restrictions on a repeated-letter word, gap method plus complementary counting. A full page of work.", solution: "Place consonants, count vowel gaps, then subtract the Ms-together cases, layered casework." },
  { id: "t19", section: "QA", kind: "trap", stem: "Find the sum of all divisors of 8,640 that are divisible by 6 but not by 8.", why: "Prime-factorise, build a constrained divisor sum, then subtract a sub-family, three-stage bookkeeping for one mark.", solution: "8640 = 2⁶·3³·5, the constrained sigma needs two full divisor-sum computations." },
  { id: "t20", section: "QA", kind: "trap", stem: "If log₁₂ 27 = a, express log₆ 16 in terms of a.", why: "Base-changing between composite bases is a known derivation, and known to take two minutes of careful algebra.", solution: "Route both logs through log 2 and log 3 via a = 3log3/(2log2 + log3), heavy symbol pushing." },
  { id: "t21", section: "QA", kind: "trap", stem: "A alone can do a job in 45 days. He starts alone; from the second day onward, one extra worker of equal efficiency joins each day. In how many days is the job finished?", why: "A growing workforce means summing an AP of daily work, a series problem hiding in a work costume.", solution: "Cumulative work n(n+1)/2 ÷ 45 ≥ 1, then a fractional final day to resolve." },
  { id: "t22", section: "QA", kind: "trap", stem: "How many ordered pairs of integers (x, y) satisfy |x| + |y| ≤ 10 and x² + y² ≥ 64?", why: "Two overlapping regions counted over lattice points, quadrant-by-quadrant enumeration. Low yield, high minutes.", solution: "Count the diamond, subtract the circle's interior point by point, grid labour." },
  { id: "t23", section: "QA", kind: "trap", stem: "Two trains start towards each other from stations 390 km apart. After meeting, they take 4 hours and 9 hours respectively to finish. If the faster train left 30 minutes late, when do they meet?", why: "The √(ratio) meeting identity PLUS a staggered start, two layers where one alone already fills a minute.", solution: "Speed ratio √9 : √4 = 3 : 2, then redo the meeting algebra with the half-hour offset." },
  { id: "t24", section: "QA", kind: "trap", stem: "Find the compound interest on ₹40,960 at 12.5% per annum for 2 years 4 months, compounded annually.", why: "A fractional final period at an awkward rate, the (1 + r/3) tail turns this into long multiplication.", solution: "40960 × (9/8)² × (1 + 12.5/300) − principal, three chained multiplications." },
  { id: "t25", section: "QA", kind: "trap", stem: "If x + y + z = 6, x² + y² + z² = 14 and x³ + y³ + z³ = 36, find x⁵ + y⁵ + z⁵.", why: "Newton's identities, run twice, a beautiful problem that has no business inside an 8-second window.", solution: "Recover e₁, e₂, e₃, then climb the power sums p₄ → p₅ recursively." },
  { id: "t26", section: "QA", kind: "trap", stem: "A triangle has sides 13, 20 and 21. Find the distance between its incentre and circumcentre.", why: "Area, then r, then R, then Euler's OI² = R² − 2Rr, four formulas stacked for one mark.", solution: "Heron's for the area, r = Δ/s, R = abc/4Δ, then the Euler identity." },
  { id: "t27", section: "QA", kind: "trap", stem: "In a survey of 200 students, 47% like tea, 54% like coffee and 42% like juice; 12% like none, and the number liking exactly two drinks is twice the number liking all three. How many like exactly one drink?", why: "A three-set Venn where the middle regions are variables, inclusion–exclusion with algebra inside. Classic time sink.", solution: "Set all-three = t, exactly-two = 2t, and grind inclusion–exclusion for t first." },
  { id: "t28", section: "QA", kind: "trap", stem: "A watch gains 5 minutes every 3 hours and was set right at 7 a.m. on Monday. What is the true time when the watch shows 4:15 p.m. the same day?", why: "Faulty-clock conversion, a ratio of unequal 'hours' with minutes to reconcile. Error-prone and slow.", solution: "The watch runs 185 min per true 180, scale the 9h15m shown back through 36/37." },
  { id: "t29", section: "QA", kind: "trap", stem: "Find the smallest n for which 3 + 33 + 333 + … (n terms) exceeds 4 × 10¹⁰.", why: "The digit-series needs the (10ⁿ − 1) closed form and then a logarithmic size estimate, two tools for one inequality.", solution: "Sum = (10^(n+1) − 10 − 9n)/27; compare orders of magnitude carefully." },
  { id: "t30", section: "QA", kind: "trap", stem: "Bag A has 5 red and 7 blue balls; Bag B has 6 red and 4 blue. Two balls are moved from A to B, then two are drawn from B. Find the probability that both drawn balls are red.", why: "The transfer branches three ways before the draw even starts, a conditional tree, not a one-liner.", solution: "Condition on RR / RB / BB transferred, then weight three separate draws from the enlarged bag." },
  { id: "t31", section: "QA", kind: "trap", stem: "In an election among three candidates, 6% of the votes polled were invalid. The winner beat the runner-up by 588 votes and the runner-up beat the third candidate by 1,176 votes; the third got 22% of the valid votes. Find the total votes polled.", why: "Three candidates, invalid votes and two margins, simultaneous equations wearing a percentage mask.", solution: "Recover the valid-vote shares from the margins first, then unwind the 94%, several steps deep." },

  // ── LR scorers (expansion) ──
  { id: "s40", section: "LR", kind: "scorer", stem: "Find the next term: 5, 11, 23, 47, ?", why: "Each term is double-plus-one, a one-look pattern.", solution: "47 × 2 + 1 = 95." },
  { id: "s41", section: "LR", kind: "scorer", stem: "If each letter's position value is added, PEN = 35. What is the value of CAP?", why: "One stated rule, three small numbers, apply and move.", solution: "3 + 1 + 16 = 20." },
  { id: "s42", section: "LR", kind: "scorer", stem: "Odd one out: 17, 27, 37, 47.", why: "Three primes and one obvious multiple of three, recognition, not work.", solution: "27 = 3³ is the only non-prime." },
  { id: "s43", section: "LR", kind: "scorer", stem: "Ravi walks 3 km north, then 4 km east. How far is he from his starting point?", why: "A 3-4-5 triangle in plain sight, the setter chose the numbers for you.", solution: "√(9 + 16) = 5 km." },
  { id: "s44", section: "LR", kind: "scorer", stem: "A is B's brother. B is C's mother. How is A related to C?", why: "Two links, no in-laws, this resolves as fast as you read it.", solution: "A is C's maternal uncle." },
  { id: "s45", section: "LR", kind: "scorer", stem: "Complete the series: AZ, BY, CX, ?", why: "First letters ascend, second letters descend, the most rehearsed letter pattern in LR.", solution: "D forward, W backward → DW." },
  { id: "s46", section: "LR", kind: "scorer", stem: "Statements: All pens are pencils. All pencils are erasers. Does \"All pens are erasers\" definitely follow?", why: "A single transitive chain of two 'All' statements, the one syllogism that is always safe.", solution: "Yes. All A→B and All B→C forces All A→C." },
  { id: "s47", section: "LR", kind: "scorer", stem: "In a row of 40 students, Aman is 13th from the left. What is his position from the right?", why: "n + 1 − k, one substitution, never skip a rank flip.", solution: "40 + 1 − 13 = 28th." },
  { id: "s48", section: "LR", kind: "scorer", stem: "How many degrees does the minute hand of a clock sweep in 25 minutes?", why: "6° per minute is a memorised constant, multiply and go.", solution: "25 × 6° = 150°." },
  { id: "s49", section: "LR", kind: "scorer", stem: "Find the next term: 2, 3, 5, 8, 12, 17, ?", why: "Differences rise by one, visible before the timer draws breath.", solution: "Next difference 6 → 23." },
  { id: "s50", section: "LR", kind: "scorer", stem: "In a certain code, ROSE is written as QNRD. How is BLUE written?", why: "Uniform −1 shift, decode letter by letter in one pass.", solution: "Each letter steps back one: AKTD." },
  { id: "s51", section: "LR", kind: "scorer", stem: "Today is Wednesday. What day of the week will it be 30 days from now?", why: "30 mod 7, count two forward, calendar arithmetic at its cleanest.", solution: "30 = 4 weeks + 2 days → Friday." },
  { id: "s52", section: "LR", kind: "scorer", stem: "Doctor : Hospital :: Teacher : ?", why: "A workplace analogy with no second reading, instant.", solution: "School." },
  { id: "s53", section: "LR", kind: "scorer", stem: "Statements: Some cups are plates. All plates are green. Does \"Some cups are green\" definitely follow?", why: "The valid Some-plus-All chain, one diagram in the head settles it.", solution: "Yes, the cups that are plates must be green." },
  { id: "s54", section: "LR", kind: "scorer", stem: "Find the next term: 1, 8, 27, 64, ?", why: "Perfect cubes announce themselves, recognition beats calculation.", solution: "5³ = 125." },

  // ── LR traps (expansion) ──
  { id: "t32", section: "LR", kind: "trap", stem: "Twelve people sit in two parallel rows of six, row 1 facing row 2. A sits third to the right of B, who faces the person second to the left of C; D and E occupy extreme ends of different rows… Who faces the person immediately to the left of F?", why: "A two-row facing arrangement is a full puzzle set, the single question fools nobody who has bled on these before.", solution: "Both rows must be fully mapped, with every facing link, before any 'who faces whom' falls out." },
  { id: "t33", section: "LR", kind: "trap", stem: "Seven seminars A–G are scheduled Monday to Sunday, one per day. C is not on Monday; exactly two seminars fall between A and B; D is immediately after G; F is on neither end… On which day is E?", why: "Six interlocking conditions across seven days, a table, a pencil and three minutes minimum.", solution: "Only systematic slotting with backtracking pins E's day." },
  { id: "t34", section: "LR", kind: "trap", stem: "In a code language, 'sky looks blue today' is 'pa ti lo se', 'blue is calm' is 'lo mi da', and 'today feels calm' is 'se da ra'. What is the code for 'looks'?", why: "Sentence-code intersection needs a cross-elimination grid across three statements, a set-piece, not a one-liner.", solution: "Eliminate the shared codes pairwise; 'looks' is whatever survives in statement one after the full grid." },
  { id: "t35", section: "LR", kind: "trap", stem: "Statements: Only a few pens are books. No book is a diary. All diaries are boxes. Conclusions: I. Some pens are not diaries. II. Some boxes being pens is a possibility. Which conclusions follow?", why: "'Only a few' plus possibility conclusions, the syllogism variant that demands two separate diagram checks. Not an 8-second call.", solution: "Each conclusion needs its own Venn test, including a constructed possibility case." },
  { id: "t36", section: "LR", kind: "trap", stem: "P # Q means P is the mother of Q; P $ Q means P is the husband of Q; P & Q means P is the sister of Q. In A $ B # C & D # E, how is A related to E?", why: "Five symbolic links to translate and chain, one mistranslation anywhere and the answer flips. Draw-it territory.", solution: "Decode link by link into a family tree, only the full tree answers it safely." },
  { id: "t37", section: "LR", kind: "trap", stem: "Starting from his office, Karan walks 10 m south-west, 20 m south-east, 20 m north-east, then 10 m north-west, then 5 m east. How far and in which direction is he from the office?", why: "Diagonal legs force vector components, coordinate work, not compass intuition. The clock loses.", solution: "Resolve each diagonal into x-y components and sum, effectively a mini coordinate-geometry problem." },
  { id: "t38", section: "LR", kind: "trap", stem: "A die shows 1 adjacent to 2, 3 and 4 in one view, and 5 adjacent to 2, 3 and 6 in another view. Which number is opposite 3?", why: "Two-view dice reconstruction means holding the cube in your head while cross-checking both views, cheap to ask, dear to answer.", solution: "Build the net from both adjacency sets and eliminate, spatial bookkeeping." },
  { id: "t39", section: "LR", kind: "trap", stem: "Six friends have different heights. P is taller than exactly two of them; Q is shorter than R but taller than S; T is not the tallest; U is taller than P… How many distinct height orders are possible?", why: "Counting ALL consistent orders, not finding one, partial-order enumeration is casework by definition.", solution: "Fix P third from the bottom and enumerate every consistent placement of the rest." },
  { id: "t40", section: "LR", kind: "trap", stem: "A machine rearranges the input '84 word 23 fig 91 apple 16' step by step by a hidden rule, producing a new line each step until fully sorted. What is step IV for the given input?", why: "Input–output machines demand deriving the rule from an example and then simulating four full steps, a five-minute genre.", solution: "Infer the alternating number-word sort rule, then write out steps I–IV in full." },
  { id: "t41", section: "LR", kind: "trap", stem: "Nine people live on the nine floors of a building. H lives above F but below D; three people live between G and E; the one on floor 5 owns a red car… Who lives on floor 7?", why: "A floors puzzle with interleaved attributes, you solve the whole tower to answer one floor. Skip and bank the time.", solution: "The full floor grid, constraints cross-checked, is the only route to floor 7." },
  { id: "t42", section: "LR", kind: "trap", stem: "In a class of 120, every student plays at least one of cricket, football and chess. 65 play cricket, 55 football and 50 chess; 15 play all three. How many play exactly two games?", why: "Inclusion–exclusion with an 'exactly two' target, the identity is known, the arithmetic chain is where 8 seconds die.", solution: "Pairwise sum = 170 − 120 + 15 = 65; exactly-two = 65 − 3×15 = 20, a chain with two classic slip points." },
  { id: "t43", section: "LR", kind: "trap", stem: "In the sequence 8 M % 4 T A # 2 U 9 & E 5 K ! I 3, how many symbols are immediately preceded by an even number and immediately followed by a vowel?", why: "A character-scan question, every element walked with two-sided checks. Pure clerical time for a one-mark payoff.", solution: "Scan all 17 positions checking both neighbours, mechanical, slow, unforgiving." },

  // ── VA scorers (expansion) ──
  { id: "s55", section: "VA", kind: "scorer", stem: "Choose the word most nearly OPPOSITE in meaning to OBSCURE.", why: "Core-list antonym, either the word is yours or it isn't; the clock is irrelevant.", solution: "OBSCURE (unclear) → opposite: evident / clear." },
  { id: "s56", section: "VA", kind: "scorer", stem: "Choose the word closest in meaning to CANDID.", why: "High-frequency synonym, a two-second vocabulary check.", solution: "Candid = frank, open." },
  { id: "s57", section: "VA", kind: "scorer", stem: "Spot the error: \"She has been working here since five years.\"", why: "Since-versus-for is a drilled rule, durations take FOR.", solution: "'…FOR five years', 'since' needs a point of time." },
  { id: "s58", section: "VA", kind: "scorer", stem: "Fill in the blank: \"He is quite good ___ mathematics.\"", why: "Fixed preposition pairing, no context to weigh.", solution: "Good AT mathematics." },
  { id: "s59", section: "VA", kind: "scorer", stem: "Choose the correctly spelt word: (a) definately (b) definitely (c) definitly (d) definetely.", why: "Look-and-know spelling, one of the most misspelt words in the prep universe.", solution: "(b) definitely." },
  { id: "s60", section: "VA", kind: "scorer", stem: "Give one word for: \"a person who can use both hands equally well\".", why: "Straight one-word substitution off the standard list.", solution: "Ambidextrous." },
  { id: "s61", section: "VA", kind: "scorer", stem: "Fill in the blank: \"He is ___ honest man.\"", why: "Article before a vowel SOUND, the single most drilled article rule.", solution: "AN honest man (silent h)." },
  { id: "s62", section: "VA", kind: "scorer", stem: "Spot the error: \"Neither of the answers are correct.\"", why: "'Neither of' takes a singular verb, an instant flag for a prepared eye.", solution: "'Neither of the answers IS correct.'" },
  { id: "s63", section: "VA", kind: "scorer", stem: "What does the idiom \"to bite the dust\" mean?", why: "Common idiom, single meaning, recall, not reasoning.", solution: "To fail or be defeated." },
  { id: "s64", section: "VA", kind: "scorer", stem: "Choose the word closest in meaning to EPHEMERAL.", why: "Prep-list staple, short-lived is the whole answer.", solution: "Ephemeral = short-lived, fleeting." },
  { id: "s65", section: "VA", kind: "scorer", stem: "Choose the correct verb: \"The news ___ (is/are) good.\"", why: "'News' is famously singular, a rule question in disguise.", solution: "The news IS good." },
  { id: "s66", section: "VA", kind: "scorer", stem: "Complete the sentence: \"The evidence was thin, so the jury refused to ___.\"", why: "One-line completion where the logic allows exactly one verb family.", solution: "…refused to convict." },

  // ── VA traps (expansion) ──
  { id: "t44", section: "VA", kind: "trap", stem: "Five jumbled sentences on the philosophy of measurement, each beginning with 'This', 'Such' or 'It', must be arranged into a coherent paragraph.", why: "Every opener is a pronoun pointing backwards, the ordering has no anchor sentence. A 90-second maze for one mark.", solution: "With no independent opener, every sequence must be trial-fitted against the reference chains." },
  { id: "t45", section: "VA", kind: "trap", stem: "A 120-word passage has 8 numbered blanks; each option supplies all eight words, and the sets differ only at blanks 3, 6 and 8.", why: "All-or-nothing cloze, three contested blanks tested against four near-identical sets. Reading tax with no partial credit.", solution: "Locate the differing blanks first, then test each candidate in context, still a multi-read job." },
  { id: "t46", section: "VA", kind: "trap", stem: "An argument about urban planning is followed by: \"Each of the following, if true, weakens the argument EXCEPT…\"", why: "EXCEPT-weaken means evaluating all five options fully, four eliminations before the answer even appears.", solution: "Every option must be tested against the conclusion; the lone non-weakener is found by exhaustion." },
  { id: "t47", section: "VA", kind: "trap", stem: "A dense 380-word excerpt on phenomenology is followed by: \"The author's tone in the final paragraph can best be described as…\"", why: "Tone on a philosophy passage means a full careful read plus a judgement between adjacent adjectives. Never an 8-second candidate.", solution: "Only the passage's closing moves settle 'wry' versus 'sceptical', whole-text work." },
  { id: "t48", section: "VA", kind: "trap", stem: "A long sentence has four underlined parts; the options pair them: \"Which TWO parts contain errors?\"", why: "Paired-error formats square the checking work, each part needs its own verdict before any option can be picked.", solution: "All four segments must be grammar-checked independently; the combination option follows." },
  { id: "t49", section: "VA", kind: "trap", stem: "Four sentences each use the word SANCTION. Choose the option listing every sentence in which the word is used correctly.", why: "'Sanction' means both permit and punish, four contextual rulings on one slippery word. Deliberate quicksand.", solution: "Each usage must be judged against both senses; the all-correct subset comes last." },
  { id: "t50", section: "VA", kind: "trap", stem: "A six-sentence paragraph on trade policy has its FOURTH sentence removed; two of the answer options restate each other with different connectors.", why: "A mid-paragraph gap with twin options, you must track the logic on both sides of the blank. Slow by construction.", solution: "The connector direction (contrast vs continuation) is the only discriminator, and it needs both neighbours parsed." },
  { id: "t51", section: "VA", kind: "trap", stem: "Five sentences are given; four form a coherent paragraph. Identify the sentence that does NOT belong.", why: "Odd-sentence-out requires building the correct order of the other four first, a para-jumble plus an elimination.", solution: "Sequence the four linkable sentences; the stranded one is the answer, full-jumble effort either way." },
  { id: "t52", section: "VA", kind: "trap", stem: "Fill the three blanks: \"___ the committee had reservations, it approved the draft, ___ noting that the funding, ___ generous, was one-time.\" Options give connector triplets.", why: "Three interdependent connectors, each choice constrains the next. A logic chain, not a vocabulary check.", solution: "Concession–addition–concession is the only consistent triplet, verified across all three clauses." },
  { id: "t53", section: "VA", kind: "trap", stem: "Match the confusable pairs, affect/effect, elicit/illicit, principal/principle, stationary/stationery, to eight gapped sentences; the options give complete mappings.", why: "Eight contextual rulings with all-or-nothing options, one hesitation multiplies across the whole matrix.", solution: "Every sentence must be resolved before any option can be certified, clerical and slow." },
  { id: "t54", section: "VA", kind: "trap", stem: "A 70-word paragraph on behavioural economics is followed by: \"Which option best captures the essence of the paragraph?\" Two options differ only in scope.", why: "Essence questions with scope-twin options force a re-read and a fine judgement, marks per minute is terrible here.", solution: "The paragraph's qualifier decides between the twins, visible only on a careful second pass." },
];

export default SOS_BANK;
