// ============================================================
// Skip or Solve decision bank (2026-09 flow overhaul).
// The trainer no longer shows options — the student sees ONLY the
// stem and makes a CALL: "Solve it" or "Skip it" within 8 seconds.
// Every item therefore carries a deliberate classification:
//   kind: "scorer" — clean, single-concept, convertible under
//         exam pressure. The right call is SOLVE.
//   kind: "trap"   — long, multi-step, case-heavy or low-yield in
//         8 seconds. The right call is SKIP.
//   why:  one-line rationale, shown on the verdict card and in the
//         end-of-run review.
// The old get_trainer_questions RPC pulled random rows from the
// whole question bank (no trap flag, HTML/image-heavy) — a curated
// local bank is the only way every item can KNOW its right call.
// The full classification list is audited in
// "IPM Careers/Gulp-authored-questions-review.html".
// ============================================================

const SOS_BANK = [
  // ── QA scorers ──
  { id: "s01", section: "QA", kind: "scorer", stem: "The average of 5 consecutive even numbers is 40. What is the largest of them?", why: "Consecutive-number averages are a 5-second identity: middle = 40, largest = 44. Free marks.", solution: "The middle (3rd) number equals the average, 40 → numbers are 36…44. Largest = 44." },
  { id: "s02", section: "QA", kind: "scorer", stem: "If 3x − 7 = 2x + 5, what is the value of x?", why: "One-step linear equation — solving takes less time than deciding. Always convert these.", solution: "3x − 2x = 5 + 7 → x = 12." },
  { id: "s03", section: "QA", kind: "scorer", stem: "What is 15% of 240?", why: "Single percentage on a friendly number: 10% + 5% mental math. Clean scorer.", solution: "24 + 12 = 36." },
  { id: "s04", section: "QA", kind: "scorer", stem: "The product of two co-prime numbers is 117. What is their LCM?", why: "Pure definition recall — LCM of co-primes is their product. No computation at all.", solution: "For co-primes, LCM = product = 117." },
  { id: "s05", section: "QA", kind: "scorer", stem: "A shopkeeper buys an article for ₹400 and sells it for ₹460. What is the profit percent?", why: "One clean ratio: 60/400. Single-concept profit percent is always worth the attempt.", solution: "60/400 × 100 = 15%." },
  { id: "s06", section: "QA", kind: "scorer", stem: "How many diagonals does a hexagon have?", why: "Direct formula n(n−3)/2 — a memory question dressed as geometry.", solution: "6 × 3 / 2 = 9 diagonals." },
  { id: "s07", section: "QA", kind: "scorer", stem: "If log₁₀ 2 ≈ 0.301, what is log₁₀ 8?", why: "One log identity: log 8 = 3 log 2. Single step, no cases.", solution: "3 × 0.301 = 0.903." },
  { id: "s08", section: "QA", kind: "scorer", stem: "The sum of the first 20 natural numbers is:", why: "n(n+1)/2 is the most-rehearsed formula in the syllabus. Instant conversion.", solution: "20 × 21 / 2 = 210." },
  { id: "s09", section: "QA", kind: "scorer", stem: "A train 200 m long crosses a pole in 10 seconds. What is its speed in m/s?", why: "Crossing a pole = length/time. One division; classic sitter.", solution: "200 / 10 = 20 m/s." },
  { id: "s10", section: "QA", kind: "scorer", stem: "If the ratio of two numbers is 3 : 5 and their sum is 96, what is the smaller number?", why: "Ratio-sum split is a single proportional step — bankable in well under 8 seconds.", solution: "3/8 × 96 = 36." },

  // ── QA traps ──
  { id: "t01", section: "QA", kind: "trap", stem: "Find the number of positive integer solutions of 3x + 5y + 7z = 100 with x, y, z all distinct.", why: "Multi-variable case enumeration with a distinctness condition — minutes of casework, not 8 seconds.", solution: "Requires enumerating (x, y, z) families case by case — exactly the low-yield grind to skip in a timed section." },
  { id: "t02", section: "QA", kind: "trap", stem: "A cistern has three pipes A, B and C. A and B fill it in 12 and 15 hours; C empties it. Opened together at staggered one-hour intervals in the order A, B, C, the tank fills in 8 hours 24 minutes. In how many hours does C alone empty a full tank?", why: "Staggered-start pipes with a fractional total time — a three-equation setup hiding in a story. Textbook time sink.", solution: "Needs hour-by-hour work accounting before C's rate can be isolated — far beyond an 8-second window." },
  { id: "t03", section: "QA", kind: "trap", stem: "How many four-digit numbers with all distinct digits are divisible by 11 and have their digit sum equal to 18?", why: "Two simultaneous number-theory filters plus a distinct-digit sweep. Enumeration-heavy, tiny payoff.", solution: "Divisibility by 11 forces alternating-sum conditions to be crossed with digit-sum 18 — pure listing under pressure." },
  { id: "t04", section: "QA", kind: "trap", stem: "The sum of the series 1/(1·3) + 1/(3·5) + 1/(5·7) + … + 1/(97·99), multiplied by the sum 1² − 2² + 3² − 4² + … − 98² + 99², equals:", why: "Two separate series tricks chained together. Either alone is fine; multiplied, it is a deliberate time trap.", solution: "Telescoping gives 49/99; the alternating squares give 4950 — but spotting and combining BOTH inside 8 seconds is not a percentage play." },
  { id: "t05", section: "QA", kind: "trap", stem: "A, B and C run around a circular track of 1200 m at speeds 3, 5 and 7 m/s, A and C clockwise, B anticlockwise, all starting together. After how many seconds are all three together at the starting point for the second time?", why: "Three runners, mixed directions, LCM of meeting times — classic multi-layer circular-motion grind.", solution: "Needs individual lap times (400 s, 240 s, ~171.4 s) and their LCM logic — a two-minute question minimum." },
  { id: "t06", section: "QA", kind: "trap", stem: "If x + 1/x = √3, find the value of x²⁰²⁶ + 1/x²⁰²⁶ + x²⁰²³ + 1/x²⁰²³.", why: "Needs the ω/cis-30° periodicity insight plus careful index chasing. Miss one cycle and the −5 is guaranteed.", solution: "x = cis(±30°), so powers cycle with period 12 — elegant on paper, brutal on the clock." },
  { id: "t07", section: "QA", kind: "trap", stem: "Three friends invest in a business. The first invests ₹x for 4 months, the second ₹(x + 5000) for 8 months and the third ₹(x − 2000) for the full year. If the annual profit of ₹87,400 is split in proportion and the third receives ₹28,600, find x.", why: "A stacked partnership equation with three unknown-in-terms-of-x capitals — setup alone eats the 8 seconds.", solution: "Requires building 4x : 8(x+5000) : 12(x−2000) and solving the share equation — solvable, but never in 8 seconds." },

  // ── DILR / reasoning ──
  { id: "s11", section: "LR", kind: "scorer", stem: "In a certain code, CAT is written as DBU. How is DOG written in that code?", why: "One uniform +1 letter shift — decode and answer in one pass.", solution: "Each letter moves one ahead: DOG → EPH." },
  { id: "s12", section: "LR", kind: "scorer", stem: "Pointing to a photograph, Ravi says, \"She is the daughter of my grandfather's only son.\" How is the girl related to Ravi?", why: "Single-link blood relation — 'grandfather's only son' collapses to 'father' immediately.", solution: "Grandfather's only son = Ravi's father; his daughter = Ravi's sister." },
  { id: "s13", section: "LR", kind: "scorer", stem: "Find the next term: 2, 6, 12, 20, 30, ?", why: "Differences 4, 6, 8, 10 — a first-order pattern visible on sight.", solution: "Differences grow by 2 → next difference 12 → 42." },
  { id: "s14", section: "LR", kind: "scorer", stem: "Statements: All roses are flowers. Some flowers fade quickly. Does the conclusion \"some roses fade quickly\" definitely follow?", why: "A two-statement syllogism with one conclusion to test — the classic invalid 'some' transfer, judgeable on sight.", solution: "Not certain — the fading flowers need not include any roses. The certain answer is that no such conclusion follows." },
  { id: "s15", section: "LR", kind: "scorer", stem: "A clock shows 3:00. What is the angle between the hour and minute hands?", why: "Standard clock position with the minute hand at 12 — pure formula recall.", solution: "3 × 30° = 90°." },
  { id: "t08", section: "LR", kind: "trap", stem: "Eight people P–W sit around a circular table, four facing the centre. P sits third to the left of the one facing away opposite Q; exactly two sit between R and S counted clockwise from R; T faces V, who is not adjacent to Q or W. Who sits second to the right of U?", why: "A full facing-direction circular arrangement compressed into one question — this is a 4-minute puzzle set, not one answer.", solution: "Needs the entire seating chart with facing directions resolved before any single position falls out." },
  { id: "t09", section: "LR", kind: "trap", stem: "Five colleagues each made two statements about who broke the printer; exactly one of each person's statements is true and exactly one colleague is guilty. From the ten statements, identify the culprit.", why: "Truth-liar grids demand testing assumptions per suspect. Deep casework in a shallow-time trainer.", solution: "Requires assuming each suspect guilty in turn and checking all ten half-true constraints — pure elimination labour." },
  { id: "t10", section: "LR", kind: "trap", stem: "In a family of nine across three generations with two married couples per generation, M is the only nephew of N, whose mother-in-law O is the paternal grandmother of P… How is Q related to the sister-in-law of M's father?", why: "Nine-member, three-generation tree with in-law links — drawing it costs multiples of your 8 seconds.", solution: "Only a full family tree resolves it; the phrasing is engineered to be unsolvable at a glance." },
  { id: "t11", section: "LR", kind: "trap", stem: "A cube is painted red on two opposite faces, blue on two adjacent faces and left unpainted elsewhere, then cut into 216 smaller cubes. How many small cubes have exactly one blue face and no red face?", why: "6×6×6 painted-cube with mixed adjacent/opposite colouring — visual bookkeeping the clock will not forgive.", solution: "Needs face-by-face accounting of edge overlaps between the blue faces and red neighbours — a grid-paper question." },

  // ── VA scorers & traps ──
  { id: "s16", section: "VA", kind: "scorer", stem: "Choose the word most nearly OPPOSITE in meaning to FRUGAL.", why: "Direct antonym of a core prep-list word — vocabulary is either known or not; no time cost either way.", solution: "FRUGAL means sparing with money — the opposite is extravagant." },
  { id: "s17", section: "VA", kind: "scorer", stem: "Spot the error: \"Each of the students have submitted their assignment.\"", why: "'Each of' + verb agreement is one of the five most-drilled grammar rules. Instant call.", solution: "'Each' is singular → 'Each of the students HAS submitted…'." },
  { id: "s18", section: "VA", kind: "scorer", stem: "Fill in the blank: \"She is quite different ___ her sister.\"", why: "Single preposition-usage rule, no context needed.", solution: "Different FROM her sister." },
  { id: "s19", section: "VA", kind: "scorer", stem: "Choose the correctly spelt word: (a) occassion (b) occasion (c) ocassion (d) occasionn.", why: "Spelling recognition is a look-and-know item — zero working required.", solution: "(b) occasion." },
  { id: "t12", section: "VA", kind: "trap", stem: "Arrange six jumbled sentences (A–F) about the history of central banking into a coherent paragraph, where three sentences begin with pronoun references and two are near-duplicates in theme.", why: "Six-sentence para-jumbles with pronoun webs routinely eat 90+ seconds and still miss. Low yield per second.", solution: "Requires testing multiple orderings against the pronoun chains — the definition of a time trap in VA." },
  { id: "t13", section: "VA", kind: "trap", stem: "A 450-word passage on monetary policy follows, with the question: \"Which of the following, if true, would MOST weaken the author's secondary argument in paragraph three?\"", why: "A full passage read for one inference mark — never convertible in 8 seconds, whatever your reading speed.", solution: "The question demands locating and negating a secondary argument — full-passage work by design." },
  { id: "t14", section: "VA", kind: "trap", stem: "Match eight idioms in Column I with eight scrambled meanings in Column II, then pick the option giving all eight pairs correctly.", why: "All-eight matching means one unknown idiom sinks the whole item. High risk, matrix-checking overhead.", solution: "Even with six known pairs, verifying the full option matrix against the remaining two costs minutes." },
];

export default SOS_BANK;
